SET NOCOUNT ON;


SELECT
    CAST(CEILING(TB.AVG_SALARY - TB.AVG_SALARY_WITHOUT_ZERO) AS INT)
FROM (
    SELECT
        AVG(CAST(Salary AS FLOAT)) AS AVG_SALARY,
        AVG(CAST(REPLACE(CAST(Salary AS VARCHAR(MAX)),'0','') AS FLOAT)) AS AVG_SALARY_WITHOUT_ZERO
    FROM
        EMPLOYEES
) AS TB;

go